#!/usr/bin/env node
// Build out.tar.xz — the one file the npm tarball carries — from out/, and pin it.
//
//   node scripts/pack-out.mjs [--force]
//
// The tree is 142 MB of archives and headers. As 2278 loose files that is a 38 MB
// tarball and 2278 requests from a CDN; as one xz archive it is 21 MB and one
// request, and `llvm-wasm-unpack` puts the tree back. out/ stays in the repository
// (it is what the pipeline writes) and is excluded from the tarball by `files`.
//
// The archive is rebuilt when it is missing, when --force is given, or when out/ has
// changed under it: a stale archive would publish the wrong archives silently, which
// is exactly the failure `npm pack` should not be able to have.
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { readdir, readFile, rm, stat, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { checkOut } from './out-checks.mjs';

// What the archive restores: the archives and headers, and the compatibility layer a
// consumer has to link with them. The last one is small, and shipping it inside the
// archive is what makes an unpacked directory usable as `$LLVM_WASM` on its own.
const MEMBERS = ['out', 'wasi-compat'];

const root = fileURLToPath(new URL('..', import.meta.url));
const archive = join(root, 'out.tar.xz');
const receipt = `${archive}.json`;

const force = process.argv.includes('--force');

const { problems, archives } = await checkOut(root);
if (problems.length) {
	console.error('Cannot pack: the built libLLVM is not complete.');
	for (const problem of problems) console.error(`  ${problem}`);
	process.exit(1);
}

const tarTo = (args) => execFileSync('tar', args, { cwd: root, stdio: ['ignore', 'pipe', 'inherit'] }).toString();

/** The newest mtime under a directory, which is when the tree last changed. */
async function newest(dir) {
	let latest = 0;
	for (const entry of await readdir(dir, { withFileTypes: true })) {
		const path = join(dir, entry.name);
		latest = Math.max(latest, entry.isDirectory() ? await newest(path) : (await stat(path)).mtimeMs);
	}
	return latest;
}

const current = await stat(archive).catch(() => null);
if (force || !current || current.mtimeMs < (await newest(join(root, 'out')))) {
	console.log(current ? 'rebuilding out.tar.xz (out/ is newer)' : 'building out.tar.xz');
	await rm(archive, { force: true });
	// Cross-platform on purpose: `tar -cJf` is Windows' bsdtar, macOS' bsdtar and GNU
	// tar alike, and every one of them can read it back.
	tarTo(['-cJf', archive, ...MEMBERS]);
}

const bytes = (await stat(archive)).size;
const digest = createHash('sha256').update(await readFile(archive)).digest('hex');

// The archive has to hold what the unpack promises, or the tarball is a 21 MB lie.
const listed = tarTo(['-tJf', archive]);
for (const member of MEMBERS) {
	if (!listed.includes(`${member}/`)) {
		console.error(`out.tar.xz does not contain ${member}/`);
		process.exit(1);
	}
}
for (const name of ['libLLVMCore.a', 'libLLVMWebAssemblyCodeGen.a', 'libLLVMSupport.a']) {
	if (!listed.includes(`out/lib/${name}`)) {
		console.error(`out.tar.xz does not contain out/lib/${name}`);
		process.exit(1);
	}
}

// The receipt is what `llvm-wasm-unpack` checks the archive against before extracting
// it, so a corrupted download is a message rather than a half-unpacked toolchain.
await writeFile(
	receipt,
	`${JSON.stringify(
		{
			file: 'out.tar.xz',
			bytes,
			sha256: digest,
			files: listed.split('\n').filter(Boolean).length,
			archives: archives.length,
			note: 'Generated by scripts/pack-out.mjs. llvm-wasm-unpack verifies against this.'
		},
		null,
		2
	)}\n`
);

console.log(`out.tar.xz: ${(bytes / 1e6).toFixed(1)} MB, ${archives.length} archives, sha256 ${digest.slice(0, 16)}…`);
