#!/usr/bin/env node
// Gzip each archive, and pin the payload.
//
//   node scripts/pack-out.mjs [--force]
//
// The archives ship gzipped, one file each: `out/lib/libLLVMCore.a.gz`. That is the shape
// a *browser* can use — `DecompressionStream` inflates gzip and nothing else, and one
// file per archive means a page fetches only what it links, from a CDN that serves bytes
// which are already compressed.
//
// (A single `.tar.xz` of the whole tree would halve the npm tarball, 22 MB against ~37,
// but a page cannot open it: xz needs a decoder a browser does not have, and reaching one
// archive would mean inflating all 142 MB. The browser is the target, so the tarball pays.)
//
// `out/lib/*.a` stays in the repository — it is what the pipeline writes — and `files`
// keeps it out of the tarball. What ships is the `.gz` beside it, and the headers, which a
// linked build needs as files and a browser never wants.
import { createHash } from 'node:crypto';
import { readFile, stat, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { gzipSync } from 'node:zlib';

import { checkOut } from './out-checks.mjs';

const root = fileURLToPath(new URL('..', import.meta.url));
const lib = join(root, 'out', 'lib');
const receiptsPath = join(root, 'src', 'asset-receipts.js');

const force = process.argv.includes('--force');

const { problems, archives } = await checkOut(root);
if (problems.length) {
	console.error('Cannot pack: the built libLLVM is not complete.');
	for (const problem of problems) console.error(`  ${problem}`);
	process.exit(1);
}

const receipts = {};
let repacked = 0;

for (const name of archives.sort()) {
	const source = join(lib, name);
	const gzipped = `${source}.gz`;
	const [raw, existing] = await Promise.all([stat(source), stat(gzipped).catch(() => null)]);

	// Re-gzip only what changed, so this is fast on the common path and correct on the
	// rare one — a stale .gz would publish bytes that no longer match the receipt.
	if (force || !existing || existing.mtimeMs < raw.mtimeMs) {
		await writeFile(gzipped, gzipSync(await readFile(source), { level: 9 }));
		repacked += 1;
	}

	const bytes = await readFile(gzipped);
	receipts[name] = {
		bytes: bytes.byteLength,
		raw: raw.size,
		sha256: createHash('sha256').update(bytes).digest('hex')
	};
}

const rawTotal = Object.values(receipts).reduce((sum, receipt) => sum + receipt.raw, 0);
const gzippedTotal = Object.values(receipts).reduce((sum, receipt) => sum + receipt.bytes, 0);

// Committed on purpose: a receipt is only useful if it is the one the released package
// shipped with, and both `src/index.js` and `bin/llvm-wasm-unpack.mjs` check reads against it.
await writeFile(
	receiptsPath,
	`// Generated by scripts/pack-out.mjs — do not edit by hand.
//
// The archives as they ship: one gzipped file each, among the headers under out/. Every
// read is checked against these receipts, so a stale copy, a truncated download or a host
// serving something else is named rather than linked into a toolchain that then fails
// somewhere stranger. ${archives.length} archives, ${(gzippedTotal / 1e6).toFixed(1)} MB gzipped
// from ${(rawTotal / 1e6).toFixed(1)} MB.
//
// Re-pin with \`node scripts/pack-out.mjs\` after rebuilding the archives.

export const ASSET_RECEIPTS = ${JSON.stringify(receipts, null, '\t')};

/** Where the shipped archives live inside the package. */
export const ASSETS_DIR = 'out/lib';

/** The compatibility layer, which has to be linked with them. */
export const COMPAT_DIR = 'wasi-compat';
`
);

console.log(
	`${archives.length} archives: ${(rawTotal / 1e6).toFixed(1)} MB raw, ${(gzippedTotal / 1e6).toFixed(1)} MB gzipped` +
		(repacked ? ` (${repacked} gzipped now)` : ' (all current)')
);
